name: Deploy Release
run-name: Deploy release ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (e.g, v1.2.3 or v1.2.3-beta.1)
        required: true
        default: v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.1.0

      - name: Install necessary dependencies
        run: pnpm install --frozen-lockfile

      - name: Run deploy release script
        env:
          BAKIT_APP_SLUG: ${{ secrets.BAKIT_APP_SLUG }}
          BAKIT_APP_ID: ${{ secrets.BAKIT_APP_ID }}
          BAKIT_APP_INSTALLATION_ID: ${{ secrets.BAKIT_APP_INSTALLATION_ID }}
          BAKIT_APP_PRIVATE: ${{ secrets.BAKIT_APP_PRIVATE }}
        run: |
          pnpm exec tsx scripts/deploy-release.ts --version="${{ github.event.inputs.version }}"
